classDiagram
    class Vehicle {
        +Brand : string
        +Speed : int
        +Position : int
        +Move() : void
    }
    class Bicycle {
        +RingBell() : void
    }
    Vehicle <|-- Bicycle
