classDiagram
    class Vehicle {
        <<abstract>>
        +Brand : string
        +Speed : int
        +Position : int
        +Move()* : void
    }
    class Car {
        +Move() : void
    }
    class Bicycle {
        +Move() : void
    }
    Vehicle <|-- Car
    Vehicle <|-- Bicycle
