%%{init: {'theme': 'base', 'themeVariables': { 'primaryTextColor': '#000000', 'fontSize': '50px'}}}%%
flowchart LR
    N8(("<div style='width:80px;height:80px;line-height:80px;text-align:center'>8</div>")) ~~~ N1["<div style='width:80px;height:80px;line-height:80px;text-align:center'>1</div>"] ~~~ N7["<div style='width:80px;height:80px;line-height:80px;text-align:center'>7</div>"] ~~~ N3(("<div style='width:80px;height:80px;line-height:80px;text-align:center'>3</div>")) ~~~ N5(("<div style='width:80px;height:80px;line-height:80px;text-align:center'>5</div>")) ~~~ N2["<div style='width:80px;height:80px;line-height:80px;text-align:center'>2</div>"]

    style N8 fill:#ffb3ba,stroke:#000,stroke-width:4px,color:#000
    style N1 fill:#caffbf,stroke:#000,stroke-width:4px,color:#000
    style N7 fill:#ffb3ba,stroke:#000,stroke-width:4px,color:#000
    style N3 fill:#ffb3ba,stroke:#000,stroke-width:4px,color:#000
    style N5 fill:#caffbf,stroke:#000,stroke-width:4px,color:#000
    style N2 fill:#caffbf,stroke:#000,stroke-width:4px,color:#000
